#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    x_axis,         sensorAccelerometer)
#pragma config(Sensor, in2,    y_axis,         sensorAccelerometer)
#pragma config(Sensor, in3,    yaw,            sensorGyro)
#pragma config(Sensor, in7,    autonomousSelect, sensorPotentiometer)
#pragma config(Sensor, in8,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, I2C_1,  left,           sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  right,          sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           driveRightFront, tmotorVex393, openLoop, encoder, encoderPort, I2C_2, 1627776)
#pragma config(Motor,  port2,           driveLeftFront, tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           rightArm1,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port4,           leftArm1,      tmotorVex393, openLoop)
#pragma config(Motor,  port5,           rightArm2,     tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           leftArm2,      tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port7,           intakeRight,   tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           intakeLeft,    tmotorVex393, openLoop)
#pragma config(Motor,  port9,           driveRightBack, tmotorVex393, openLoop)
#pragma config(Motor,  port10,          driveLeftBack, tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/********\
*Settings*
\********/

int threshold = 10;      // Threshold for driving deadzone
int driveSlow = 1;       // Starting at 1, the greater the number, the slower it goes, formula:(value/driveSlow = speed)
int intakeSpeed = 80;    // Speed of the intake
int armSpeed = 127;      // Speed of arm for upward movment
int armDownSpeed = 127;  // Speed of arm for downward movement
int slowSpeed = 20;      // Speed of arm for downward movement while near the bottom to prevent the arm from slamming into the ground
int slowdPosition = 400; // Position to start slowing down the arm
int maxHeight = 1700;    // Maximum code allowed pot value number for arm to get to so the pot dosent break.
int scoreHeight = 1600;  // Height of arm that is optimum for scoring
int zeroValue = 255;     // Value of pot at zero arm height

/*********************\
*Function Declarations*
\*********************/

void lowerArm();
void raiseArm();
void drive();
void intake1();
void stopArm();
void positionArm(int position);
int armPosition();


void zeroEncoders();

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{


}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{

}

/*********\
*Functions*
\*********/


void lowerArm()
{
	// Arm lowers
	// Speed decreases as we near the bottom.
	if(armPosition() > slowdPosition)
	{
		motor[rightArm1] = -armDownSpeed;
		motor[rightArm2] = -armDownSpeed;
		motor[leftArm1]  = -armDownSpeed;
		motor[leftArm2]  = -armDownSpeed;
		} else if(armPosition() > zeroValue){
		motor[rightArm1] = -slowSpeed;
		motor[rightArm2] = -slowSpeed;
		motor[leftArm1]  = -slowSpeed;
		motor[leftArm2]  = -slowSpeed;
	}
	else{
		stopArm();
	}
}





void raiseArm()
{// Arm goes up.
	if(armPosition() < maxHeight){
		motor[rightArm1] = armSpeed;
		motor[rightArm2] = armSpeed;
		motor[leftArm1]  = armSpeed;
		motor[leftArm2]  = armSpeed;
		}else{
		stopArm();
	}
}


void stopArm()
{// This is to stop the arm motors.
	motor[rightArm1] = 0;
	motor[rightArm2] = 0;
	motor[leftArm1]  = 0;
	motor[leftArm2]  = 0;
}

void positionArm(int position)
{// Positions arm to a specified place

	if (armPosition() < position )
	{
		while(armPosition() < position){
			raiseArm();
		}
		stopArm();
	} else if (armPosition() > position)
	{
		while (armPosition() > position){
			lowerArm();

		}
	}
}


int armPosition()
{// Returns pot value
	return (SensorValue[potentiometer]);
}

void zeroEncoders()
{
	SensorValue[left]  = 0;
	SensorValue[right] = 0;
}
